{
//=========Macro generated from canvas: tlegend/
//=========  (Fri Mar 30 10:58:39 2018) by ROOT version5.34/34
   TCanvas *tlegend = new TCanvas("tlegend", "",497,76,305,390);
   gStyle->SetOptStat(0);
   tlegend->Range(0,0,1,1);
   tlegend->SetFillColor(0);
   tlegend->SetBorderMode(0);
   tlegend->SetBorderSize(0);
   tlegend->SetTickx(1);
   tlegend->SetTicky(1);
   tlegend->SetLeftMargin(0.17);
   tlegend->SetRightMargin(0.08);
   tlegend->SetTopMargin(0.05);
   tlegend->SetBottomMargin(0.15);
   tlegend->SetFrameLineColor(0);
   tlegend->SetFrameBorderMode(0);
   
   TLegend *leg = new TLegend(0.002212389,0.1490066,0.9977876,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.08);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","Unfolded","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("dataUnfSq_ix6_in0","1st iter.","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(40);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(40);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("dataUnfSq_ix6_in1","2nd iter.","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(41);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(41);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("dataUnfSq_ix6_in2","3rd iter.","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(43);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(43);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("dataUnfSq_ix6_in3","4th iter.","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(45);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(45);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("dataUnfSq_ix6_in4","5th iter.","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(32);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(32);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("dataUnfSq_ix6_in5","6th iter.","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(47);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(47);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("dataUnfSq_ix6_in6","7th iter.","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(46);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(46);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("dataUnfSq_ix6_in7","8th iter.","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(48);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(48);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   tlegend->Modified();
   tlegend->cd();
   tlegend->SetSelected(tlegend);
}
